# Generated by Django 5.0.6 on 2024-06-05 18:37

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='img/food_product')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=150, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'FoodProduct',
                'verbose_name_plural': 'FoodProducts',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('orders', models.TextField()),
                ('nop', models.IntegerField()),
                ('special_request', models.TextField()),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='img/team')),
            ],
        ),
    ]
