# Generated by Django 5.0.6 on 2024-06-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='is_best',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='is_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='is_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='is_lunch',
            field=models.BooleanField(default=False),
        ),
    ]
